# July 10, 2025

## Extension of July 8

## Questions

### Q1. Write custom functions for accuracy and mean square error using numpy and compare your result with sklearn metric module functions.

In [5]:
import numpy as np
import sklearn as sk
def calculate_mse (y_true, y_pred):
  y_true=np.array(y_true)
  y_pred=np.array(y_pred)
  if len(y_true) != len(y_pred):
    raise ValueError("Input arrays y_true and y_pred must have the same length.")
  squared_differences = (y_true - y_pred)**2
  mse = np.mean(squared_differences)
  return mse
calculate_mse(y_true, y_pred)

np.float64(0.5)

In [6]:
def calculate_acc (y_true, y_pred):
  y_true=np.array(y_true)
  y_pred=np.array(y_pred)
  if len(y_true) != len(y_pred):
    raise ValueError("Input arrays y_true and y_pred must have the same length.")
  correct_predictions = ( y_true == y_pred )
  num_correct = np.sum(correct_predictions)
  accuracy = num_correct / len(y_true)
  return accuracy
calculate_acc(y_true, y_pred)

np.float64(0.5)

In [7]:
data = np.array([[1], [2], [3], [4], [5]])
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler=MinMaxScaler()
std_scaler = StandardScaler()
scaler.fit(data)
std_scaler.fit(data)
print(scaler.transform(data))
print(std_scaler.transform(data))

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


### Q2. Implement a custom min-max scaler function and compare the output with sklearn library min-max scaling function.

In [28]:
import numpy as np
def min_max (data):
  data=np.array(data)
  min_value = np.min(data)
  max_value = np.max(data)
  scaled_data = []
  for i in range(len(data)):
    scaled_value = (data[i] - min_value) / (max_value - min_value)
    scaled_data.append(scaled_value)
  return np.array(scaled_data)
def std_scaler (data):
  data=np.array(data)
  mean_value = np.mean(data)
  std_value = np.std(data)
  scaled_data = []
  for i in range(len(data)):
    scaled_value = (data[i] - mean_value) / std_value
    scaled_data.append(scaled_value)
  return np.array(scaled_data)
  
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import numpy as np
data = np.array([[1], [2], [3], [4], [5]])
# Apply custom min_max function
custom_scaled_data = min_max(data)
print("Custom Min-Max Scaler Output:")
print(custom_scaled_data)
#Apply custom StandardScaler function
custom_scaled_data = std_scaler(data)
print("\nCustom StandardScaler Output:")
print(custom_scaled_data)
# Apply scikit-learn MinMaxScaler
scaler = MinMaxScaler()
sklearn_scaled_data = scaler.fit_transform(data)
print("\nScikit-learn MinMaxScaler Output:")
print(sklearn_scaled_data)
# Apply scikit learn StandardScaler
scaler = StandardScaler()
sklearn_scaled_data = scaler.fit_transform(data)
print("\nScikit-learn StandardScaler Output:")
print(sklearn_scaled_data)

Custom Min-Max Scaler Output:
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

Custom StandardScaler Output:
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

Scikit-learn MinMaxScaler Output:
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

Scikit-learn StandardScaler Output:
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


### Q3. Implement a custom library with following modules and functionalities.
- Preprocessing
    - MinMaxScaler
    - StandardScaler
- Metrics
    - Accuracy_score
    - Mean_sqaured_error
    - mean_absolute_error
    - mean absolute percentage error
- Model_Selection
    - train test split

In [10]:
%%writefile metrics.py
import numpy as np
def mean_squared_error(y,yhat):
  return np.mean((y ==yhat)**2)

Writing metrics.py


In [12]:
def mean(num):
  tot=sum(num)
  length=len(num)
  mean=tot/length
  print("mean:", mean)

def median(num):
  sort=sorted(num)
  length=len(num)
  if (length%2==0):
    med=(sort[length//2]+sort[length//2-1])/2
  else:
    med=sort[length//2]
  print("Median:", med)

def mode(numbers):

  if not numbers:
    print("The list is empty, so there is no mode.")

  counts = {}
  for number in numbers:
    counts[number] = counts.get(number, 0) + 1

  if not counts:
      print("No numbers found to calculate mode.")

  max_frequency = 0
  for frequency in counts.values():
    if frequency > max_frequency:
      max_frequency = frequency

  all_same_frequency = True
  for freq in counts.values():
      if freq != max_frequency:
          all_same_frequency = False
          break

  if all_same_frequency and max_frequency == 1 and len(numbers) > 1:
      print("All numbers appear with the same frequency, so there is no distinct mode.")

  modes = []
  for number, frequency in counts.items():
    if frequency == max_frequency:
      modes.append(number)

  if len(modes) == 1:
    print(f"The mode of the numbers is: {modes[0]}")
  else:
    modes.sort()
    print(f"The modes of the numbers are: {modes}")

In [13]:
numeric = [1,0,2,5,8,7,4,1,3,6,9,8,2,1,4,7,9,10,15,79,105]
mean(numeric)
median(numeric)
mode(numeric)

mean: 13.619047619047619
Median: 6
The mode of the numbers is: 1


In [15]:
import numpy as np

def percentile(data, percent):

  if not isinstance(data, (list, np.ndarray)):
    print("Input data must be a list or numpy array.")
    return
  if not 0 <= percent <= 100:
    print("Percentile must be between 0 and 100.")
    return

  data_sorted = np.sort(data)
  rank = (percent / 100) * (len(data_sorted) - 1)
  if rank.is_integer():
    percentile_value = data_sorted[int(rank)]
  else:
    lower_index = int(np.floor(rank))
    upper_index = int(np.ceil(rank))
    percentile_value = data_sorted[lower_index] + (rank - lower_index) * (data_sorted[upper_index] - data_sorted[lower_index])
    print(f"The {percent}th percentile is: {percentile_value}") # Removed print statement
  return percentile_value

In [18]:
def quart(data):
  q1=percentile(data,25)
  q2=percentile(data,50)
  q3=percentile(data,75)
  low_bound=q1-1.5*(q3-q1)
  high_bound=q3+1.5*(q3-q1)
  outliers=[x for x in data if x<low_bound or x>high_bound]
  print("Low bound:",low_bound)
  print("High bound:",high_bound)
  if outliers:
    print("Outliers:",outliers)
  else:
    print("No outliers")

In [19]:
basha = [10,11,12,13,14,15,16,17,18,19,20,21]
percentile(basha,50)
percentile(basha,70)
percentile(basha,20)
percentile(basha,25)
quart(basha)

The 50th percentile is: 15.5
The 70th percentile is: 17.7
The 20th percentile is: 12.2
The 25th percentile is: 12.75
The 25th percentile is: 12.75
The 50th percentile is: 15.5
The 75th percentile is: 18.25
Low bound: 4.5
High bound: 26.5
No outliers


In [21]:
def variance(data):
    data = np.array(data)
    mean_value = np.mean(data)
    squared_differences = (data - mean_value)**2
    variance = np.mean(squared_differences)
    return variance

In [22]:
def standard_deviation(data):
  var = variance(data)
  std_dev = np.sqrt(var)
  print("Variance:", var)
  print("Standard Deviation:", std_dev)

In [23]:
ramesh = [1,2,3,1,2,3,2,1,3,2,1,2,3,2,2,1,0,2,3,1,2,3]
variance(ramesh)
standard_deviation(ramesh)

Variance: 0.7190082644628099
Standard Deviation: 0.8479435502808014


In [24]:
def calculate_zscore(data):
    data = np.array(data)
    mean_value = np.mean(data)
    std_value = np.std(data)
    if std_value == 0:
        print("Standard deviation is zero. Cannot calculate z-scores.")
        return np.zeros_like(data)

    z_scores = (data - mean_value) / std_value
    return z_scores

In [25]:
suku = [10,20,30,40,50,60,70,80,90,100]
calculate_zscore(suku)

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [26]:
import math
def correlation(x,y):
  if len(x) != len(y) or not x or not y:
    return None
  meanx= sum(x)/len(y)
  meany= sum(y)/len(y)
  numerator=sum([(x[i]-meanx)*(y[i]-meany) for i in range(len(x))])
  denominator=math.sqrt(sum([(xi-meanx)**2 for xi in x]) * sum([(yi-meany)**2 for yi in y]))
  return numerator/denominator if denominator else None

In [27]:
import math
x = [1,2,3,4,5]
y = [2,3,4,5,6]
correlation(x,y)

1.0